version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEF_ARN>"
        LoadBalancerInfo:
          ContainerName: "adama-web"  # Ensure this matches your container name
          ContainerPort: 80  # Change based on your container's exposed port
