version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-1"
    IMAGE_TAG: "latest"
    AWS_ACCOUNT_ID: "600941914653"
    ECR_REGISTRY: "600941914653.dkr.ecr.ap-south-1.amazonaws.com"
    ECR_REPOSITORY: "adama_internal"
    TASK_DEF_NAME: "Adama-BG"
    S3_BUCKET_NAME: "adama-ecs-bg"
    CODEDEPLOY_APPLICATION_NAME: "Leo1_Frontend_BG_App"
    CODEDEPLOY_DEPLOYMENT_GROUP_NAME: "Leo1_Frontend_BG_DG"
    

  secrets-manager:
    GITHUB_TOKEN: "github-token-id"  # AWS Secrets Manager for GitHub Token

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y jq
      - curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
      - chmod +x /usr/local/bin/yq

  pre_build:
    commands:
      - echo "Checking project directory..."
      - pwd
      - ls -l  # Debugging: List files to verify docker-compose.yml is present
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$ECR_REGISTRY"
      - export IMAGE_TAG=$CODEBUILD_BUILD_NUMBER

  build:
    commands:
      - echo "Building Docker images using Docker..."
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG -f login-app/Dockerfile .
      - echo "Listing built images..."
      - docker images  # Debugging step to check built image names
      - echo "Tagging images..."
      - docker tag adama_internal:latest "$ECR_REGISTRY/$ECR_REPOSITORY:app-$IMAGE_TAG"
      - echo "Pushing Docker images to ECR..."
      - docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
